trigger:
  batch: true
  branches:
    include:
    - master
    - dev

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'release'
  projects: 'src/**/*.csproj'

steps:
- task: UseDotNet@2
  displayName: 'Use Dotnet'
  inputs:
    packageType: 'sdk'
    version: '10.0.x'

- script: dotnet --info
  displayName: 'Show .NET SDK info'

- task: DotNetCoreCLI@2
  displayName: 'restoring'
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'building'
  inputs:
    command: 'build'
    projects: '$(projects)'
    arguments: '-c $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'testing'
  inputs:
    command: 'test'
    projects: '**/*.Tests.csproj'
    arguments: '-c $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'packing'
  condition: eq(variables['build.sourceBranch'], 'refs/heads/dev')
  inputs:
    command: 'custom'
    projects: '$(projects)'
    custom: 'pack'
    arguments: '-c $(buildConfiguration) --no-build -o $(Build.ArtifactStagingDirectory) --version-suffix dev$(Build.BuildNumber)'

- task: DotNetCoreCLI@2
  displayName: 'packing'
  condition: eq(variables['build.sourceBranch'], 'refs/heads/master')
  inputs:
    command: 'custom'
    projects: '$(projects)'
    custom: 'pack'
    arguments: '-c $(buildConfiguration) --no-build -o $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'packages'
    publishLocation: 'Container'